### PR TITLE
Replace usage of `File.exists?` with `File.exist?`

### PR DESCRIPTION
**Pull request by PikachuEXE**
Former removed in Ruby 3.2

### CODE REVIEW

**Comment by jcamenisch** [comment]
Thank you for this, @PikachuEXE. Could you separate this into single-topic PR's? I.e., just make the one change in the title, and I'll merge that as one commit. Then we can discuss the config changes separately.

**Comment by jcamenisch** [comment]
Sorry for letting the CI build fall into disrepair. I wasn't following the changes over at Travis CI. I have signed up for their beta now to (hopefully) allow migration from travis-ci.org over to travis-ci.com.

The Github actions idea is attractive long term. I will try to get a quick build with Travis, and then take a closer look at the Github Actions approach. Perhaps we can get it to also do checks on the PR thread, block merging, etc. Right now I don't see the build results.

**Comment by PikachuEXE** [comment]
Commit for config change removed

**Comment by PikachuEXE** [comment]
Would this be released soon?

**Comment by jcamenisch** [comment]
Good question, @PikachuEXE. Thank you for reminding me. I pushed a new release candidate this morning, but I haven't tested the gem yet, and I still need to iron out the CI setup. I hope that helps.

I will move this toward v 1.0, since the API is essentially complete as far as I can tell. The only updates I foresee will be for compatibility with new versions of Ruby, Minitest, etc.

**Comment by PikachuEXE** [comment]
Great! Now I am just waiting for nokogiri to make a release before testing (or I might just test with [its rc version](https://github.com/sparklemotion/nokogiri/releases/tag/v1.14.0.rc1)

**Pull request merged**
